"""certificate modified

Revision ID: 038a1b14b505
Revises: f8128447cc75
Create Date: 2024-02-18 06:26:25.788881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038a1b14b505'
down_revision = 'f8128447cc75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('course_amount', sa.String(), nullable=True))
    op.drop_column('certificates', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('amount', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('certificates', 'course_amount')
    # ### end Alembic commands ###
