"""app_data table added

Revision ID: 05d4d94220ca
Revises: f34a3e2056af
Create Date: 2024-03-15 17:03:07.663196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05d4d94220ca'
down_revision = 'f34a3e2056af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_data',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('app_name', sa.String(), nullable=True),
    sa.Column('app_logo', sa.String(), nullable=True),
    sa.Column('mobile_app_version', sa.String(), nullable=True),
    sa.Column('is_maintenance', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_unique_constraint(None, 'edu_degree', ['uuid'])
    op.create_unique_constraint(None, 'edu_specialization', ['uuid'])
    op.create_unique_constraint(None, 'explore_category', ['uuid'])
    op.create_unique_constraint(None, 'industry', ['uuid'])
    op.create_unique_constraint(None, 'job_title', ['uuid'])
    op.drop_column('settings', 'is_maintenance')
    op.drop_column('settings', 'mobile_app_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('mobile_app_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('is_maintenance', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'job_title', type_='unique')
    op.drop_constraint(None, 'industry', type_='unique')
    op.drop_constraint(None, 'explore_category', type_='unique')
    op.drop_constraint(None, 'edu_specialization', type_='unique')
    op.drop_constraint(None, 'edu_degree', type_='unique')
    op.drop_table('app_data')
    # ### end Alembic commands ###
