"""Tags added and  modified

Revision ID: 09debe05769d
Revises: 7ea745b63e9d
Create Date: 2024-02-16 13:14:46.748787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09debe05769d'
down_revision = '7ea745b63e9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('reviews', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'tags')
    op.drop_column('comments', 'tags')
    # ### end Alembic commands ###
