"""Personal table modified

Revision ID: 0c1f216a8979
Revises: 5de7a337020d
Create Date: 2024-04-03 09:31:02.844301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1f216a8979'
down_revision = '5de7a337020d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'reports', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='unique')
    # ### end Alembic commands ###
