"""post module changes done

Revision ID: 0f874862dd38
Revises: 47db6aad92b9
Create Date: 2022-12-16 23:44:01.502925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f874862dd38'
down_revision = '47db6aad92b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('comments', sa.Column('is_reported', sa.Boolean(), nullable=True))
    op.drop_column('comments', 'delete_comment')
    op.drop_column('comments', 'report_comment')
    op.add_column('customs', sa.Column('country', sa.String(), nullable=True))
    op.add_column('customs', sa.Column('grade', sa.String(), nullable=True))
    op.drop_column('customs', 'contact_us')
    op.drop_column('customs', 'mobile_no')
    op.create_unique_constraint(None, 'ei_admin_management', ['uuid'])
    op.create_unique_constraint(None, 'ei_admission_details', ['uuid'])
    op.create_unique_constraint(None, 'ei_aluminies', ['uuid'])
    op.create_unique_constraint(None, 'ei_faculties', ['uuid'])
    op.create_unique_constraint(None, 'ei_program_offers', ['uuid'])
    op.create_unique_constraint(None, 'menem_logs', ['uuid'])
    op.add_column('post_likes_dislikes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('post_likes_dislikes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('post_likes_dislikes', 'is_disliked')
    op.add_column('posts', sa.Column('comments_count', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('industry', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'industry')
    op.drop_column('posts', 'comments_count')
    op.add_column('post_likes_dislikes', sa.Column('is_disliked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('post_likes_dislikes', 'updated_at')
    op.drop_column('post_likes_dislikes', 'created_at')
    op.drop_constraint(None, 'menem_logs', type_='unique')
    op.drop_constraint(None, 'ei_program_offers', type_='unique')
    op.drop_constraint(None, 'ei_faculties', type_='unique')
    op.drop_constraint(None, 'ei_aluminies', type_='unique')
    op.drop_constraint(None, 'ei_admission_details', type_='unique')
    op.drop_constraint(None, 'ei_admin_management', type_='unique')
    op.add_column('customs', sa.Column('mobile_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customs', sa.Column('contact_us', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customs', 'grade')
    op.drop_column('customs', 'country')
    op.add_column('comments', sa.Column('report_comment', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('delete_comment', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'is_reported')
    op.drop_column('comments', 'is_deleted')
    # ### end Alembic commands ###
