"""Protect account removed

Revision ID: 118d0714777d
Revises: 9a9ad17a785a
Create Date: 2024-03-28 12:21:58.373866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118d0714777d'
down_revision = '9a9ad17a785a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'protect_account')
    op.drop_constraint('verifications_MID_fkey', 'verifications', type_='foreignkey')
    op.drop_column('verifications', 'MID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications', sa.Column('MID', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('verifications_MID_fkey', 'verifications', 'users', ['MID'], ['MID'])
    op.add_column('settings', sa.Column('protect_account', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
