"""is_deleted added to personal details

Revision ID: 14dcb9330958
Revises: 36461850a904
Create Date: 2023-10-31 21:42:28.888118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14dcb9330958'
down_revision = '36461850a904'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eduinstitutes', 'mobile_no')
    op.drop_column('organizations', 'mobile_no')
    op.add_column('pa_education_info', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('pa_projects', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('pa_work_info', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('social_links', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_links', 'is_deleted')
    op.drop_column('pa_work_info', 'is_deleted')
    op.drop_column('pa_projects', 'is_deleted')
    op.drop_column('pa_education_info', 'is_deleted')
    op.add_column('organizations', sa.Column('mobile_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('eduinstitutes', sa.Column('mobile_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
