"""Added fields to profile and core

Revision ID: 2da7623785f1
Revises: a0181aa7c042
Create Date: 2023-03-04 18:39:57.138813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2da7623785f1'
down_revision = 'a0181aa7c042'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ei_placement_partner',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('MID', sa.String(), nullable=True),
    sa.Column('placement_partner_description', sa.String(), nullable=True),
    sa.Column('edu_institute_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['MID'], ['users.MID'], ),
    sa.ForeignKeyConstraint(['edu_institute_uuid'], ['eduinstitutes.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('businesses', sa.Column('company_size', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('head_quaters', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('established_year', sa.Integer(), nullable=True))
    op.add_column('eduinstitutes', sa.Column('placement_partner', sa.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True))
    op.add_column('eduinstitutes', sa.Column('established_year', sa.Integer(), nullable=True))
    op.add_column('eduinstitutes', sa.Column('NIRF_ranking', sa.String(), nullable=True))
    op.add_column('eduinstitutes', sa.Column('recognised_by', sa.String(), nullable=True))
    op.add_column('eduinstitutes', sa.Column('strength', sa.Integer(), nullable=True))
    op.add_column('eduinstitutes', sa.Column('student_placed', sa.Integer(), nullable=True))
    op.add_column('eduinstitutes', sa.Column('academic_facilities', sa.String(), nullable=True))
    op.add_column('eduinstitutes', sa.Column('entrance_eligibility', sa.String(), nullable=True))
    op.add_column('students', sa.Column('skills', sa.String(), nullable=True))
    op.add_column('students', sa.Column('projects', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'projects')
    op.drop_column('students', 'skills')
    op.drop_column('eduinstitutes', 'entrance_eligibility')
    op.drop_column('eduinstitutes', 'academic_facilities')
    op.drop_column('eduinstitutes', 'student_placed')
    op.drop_column('eduinstitutes', 'strength')
    op.drop_column('eduinstitutes', 'recognised_by')
    op.drop_column('eduinstitutes', 'NIRF_ranking')
    op.drop_column('eduinstitutes', 'established_year')
    op.drop_column('eduinstitutes', 'placement_partner')
    op.drop_column('businesses', 'established_year')
    op.drop_column('businesses', 'head_quaters')
    op.drop_column('businesses', 'company_size')
    op.drop_table('ei_placement_partner')
    # ### end Alembic commands ###
