"""profile/ebattle updated

Revision ID: 36461850a904
Revises: 7e97a7453f8d
Create Date: 2023-10-14 13:03:09.108526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36461850a904'
down_revision = '7e97a7453f8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('e_battles', sa.Column('title', sa.String(), nullable=True))
    op.add_column('e_battles', sa.Column('activity_url', sa.String(), nullable=True))
    op.add_column('e_battles', sa.Column('hashtags', sa.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True))
    op.add_column('e_battles', sa.Column('guests', sa.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True))
    op.add_column('e_battles', sa.Column('collab_acc', sa.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True))
    op.alter_column('e_battles', 'from_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('e_battles', 'to_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_column('e_battles', 'is_paid_battle')
    op.drop_column('e_battles', 'winner')
    op.drop_column('e_battles', 'result_date')
    op.drop_column('e_battles', 'name')
    op.drop_column('e_battles', 'amount_type')
    op.drop_column('e_battles', 'duration')
    op.drop_column('e_battles', 'amount')
    op.add_column('eduinstitutes', sa.Column('website', sa.String(), nullable=True))

    op.add_column('organizations', sa.Column('website', sa.String(), nullable=True))
    op.add_column('personals', sa.Column('location', sa.String(), nullable=True))
    op.add_column('personals', sa.Column('contact_us', sa.JSON(), nullable=True))
    op.drop_column('personals', 'country')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('personals', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('personals', 'contact_us')
    op.drop_column('personals', 'location')
    op.drop_column('organizations', 'website')
    op.drop_column('eduinstitutes', 'website')
    op.add_column('e_battles', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('e_battles', sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('e_battles', sa.Column('amount_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('e_battles', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('e_battles', sa.Column('result_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('e_battles', sa.Column('winner', postgresql.ARRAY(postgresql.UUID()), autoincrement=False, nullable=True))
    op.add_column('e_battles', sa.Column('is_paid_battle', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('e_battles', 'to_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('e_battles', 'from_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('e_battles', 'collab_acc')
    op.drop_column('e_battles', 'guests')
    op.drop_column('e_battles', 'hashtags')
    op.drop_column('e_battles', 'activity_url')
    op.drop_column('e_battles', 'title')
    
    # ### end Alembic commands ###
