"""Delete reason added 

Revision ID: 3bb1c253683c
Revises: 5402ae637181
Create Date: 2023-08-06 02:28:46.156138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb1c253683c'
down_revision = '5402ae637181'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'designations', ['uuid'])
    op.create_unique_constraint(None, 'organizations', ['uuid'])
    op.create_unique_constraint(None, 'personals', ['uuid'])
    op.add_column('users', sa.Column('delete_reason', sa.String(), nullable=True))
    op.add_column('users', sa.Column('delete_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'delete_comment')
    op.drop_column('users', 'delete_reason')
    op.drop_constraint(None, 'personals', type_='unique')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_constraint(None, 'designations', type_='unique')
    # ### end Alembic commands ###
