"""user table added

Revision ID: 4306c068ee11
Revises: f9d5e6409497
Create Date: 2024-01-30 12:40:03.571995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4306c068ee11'
down_revision = 'f9d5e6409497'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eduinstitutes', sa.Column('location', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('location', sa.String(), nullable=True))
    op.add_column('personals', sa.Column('location', sa.String(), nullable=True))
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('personals', 'location')
    op.drop_column('organizations', 'location')
    op.drop_column('eduinstitutes', 'location')
    # ### end Alembic commands ###
