"""Setting and Report Modified

Revision ID: 458dfecfec4b
Revises: e8f9efb37a09
Create Date: 2024-01-19 20:09:39.272131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458dfecfec4b'
down_revision = 'e8f9efb37a09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reports_media_uuid_fkey5', 'reports', type_='foreignkey')
    op.drop_constraint('reports_media_uuid_fkey2', 'reports', type_='foreignkey')
    op.drop_constraint('reports_media_uuid_fkey4', 'reports', type_='foreignkey')
    op.drop_constraint('reports_media_uuid_fkey3', 'reports', type_='foreignkey')
    op.drop_constraint('reports_media_uuid_fkey', 'reports', type_='foreignkey')
    op.drop_constraint('reports_media_uuid_fkey1', 'reports', type_='foreignkey')
    op.drop_column('settings', 'delete_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('delete_account', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_foreign_key('reports_media_uuid_fkey1', 'reports', 'comments', ['media_uuid'], ['uuid'])
    op.create_foreign_key('reports_media_uuid_fkey', 'reports', 'certificates', ['media_uuid'], ['uuid'])
    op.create_foreign_key('reports_media_uuid_fkey3', 'reports', 'e_battles', ['media_uuid'], ['uuid'])
    op.create_foreign_key('reports_media_uuid_fkey4', 'reports', 'posts', ['media_uuid'], ['uuid'])
    op.create_foreign_key('reports_media_uuid_fkey2', 'reports', 'users', ['media_uuid'], ['uuid'])
    op.create_foreign_key('reports_media_uuid_fkey5', 'reports', 'reviews', ['media_uuid'], ['uuid'])
    # ### end Alembic commands ###
