"""Added fields to custom like student

Revision ID: 4e724ad51460
Revises: 5ca6f2547e60
Create Date: 2023-04-06 21:19:11.584930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e724ad51460'
down_revision = '5ca6f2547e60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customs', sa.Column('skills', sa.String(), nullable=True))
    op.add_column('customs', sa.Column('projects', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customs', 'projects')
    op.drop_column('customs', 'skills')
    # ### end Alembic commands ###
