"""Student Custom to Personal & Business to Organization

Revision ID: 5402ae637181
Revises: 4e724ad51460
Create Date: 2023-07-23 22:18:56.631162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5402ae637181'
down_revision = '4e724ad51460'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designations',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('organizations',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('MID', sa.String(), nullable=True),
    sa.Column('organization_type', sa.String(), nullable=True),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('mobile_no', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('contact_us', sa.JSON(), nullable=True),
    sa.Column('social_links', sa.String(), nullable=True),
    sa.Column('company_size', sa.String(), nullable=True),
    sa.Column('head_quaters', sa.String(), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['MID'], ['users.MID'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('personals',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('MID', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('pronounce', sa.String(), nullable=True),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('institute_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('YOG', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('YOE', sa.Integer(), nullable=True),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('social_links', sa.String(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.Column('projects', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['MID'], ['users.MID'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('students')
    op.drop_table('customs')
    op.drop_table('businesses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_uuid', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('MID', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('business_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profile_photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cover_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tagline', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mobile_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('about', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_us', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('social_links', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('company_size', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('head_quaters', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('established_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['MID'], ['users.MID'], name='businesses_MID_fkey'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], name='businesses_user_uuid_fkey'),
    sa.PrimaryKeyConstraint('uuid', name='businesses_pkey'),
    sa.UniqueConstraint('uuid', name='businesses_uuid_key')
    )
    op.create_table('customs',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_uuid', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('MID', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sub_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tagline', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('about', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('YOE', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profile_photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cover_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('social_links', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pronounce', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('DOB', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('institute_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('specialization', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('YOG', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('skills', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('projects', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['MID'], ['users.MID'], name='customs_MID_fkey'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], name='customs_user_uuid_fkey'),
    sa.PrimaryKeyConstraint('uuid', name='customs_pkey'),
    sa.UniqueConstraint('uuid', name='customs_uuid_key')
    )
    op.create_table('students',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_uuid', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('MID', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tagline', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('about', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('specialization', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('YOG', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profile_photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cover_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('social_links', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('DOB', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('pronounce', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('institute_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('YOE', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('skills', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('projects', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['MID'], ['users.MID'], name='students_MID_fkey'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], name='students_user_uuid_fkey'),
    sa.PrimaryKeyConstraint('uuid', name='students_pkey'),
    sa.UniqueConstraint('uuid', name='students_uuid_key')
    )
    op.drop_table('personals')
    op.drop_table('organizations')
    op.drop_table('designations')
    # ### end Alembic commands ###
