"""Report Table Modified

Revision ID: 63cc0b77be2a
Revises: 6aa50cdadd4e
Create Date: 2024-01-16 15:05:33.822017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63cc0b77be2a'
down_revision = '6aa50cdadd4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports_table',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('reporter_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('reported_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('post_uuid', postgresql.UUID(), nullable=True),
    sa.Column('certificate_uuid', postgresql.UUID(), nullable=True),
    sa.Column('ebattle_uuid', postgresql.UUID(), nullable=True),
    sa.Column('profile_uuid', postgresql.UUID(), nullable=True),
    sa.Column('comment_uuid', postgresql.UUID(), nullable=True),
    sa.Column('report_reason', sa.String(), nullable=True),
    sa.Column('report_count', sa.Integer(), nullable=True),
    sa.Column('report_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reported_uuid'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['reporter_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports_table')
    # ### end Alembic commands ###
