"""Reset table created

Revision ID: 678d5e887ea6
Revises: a4c08b13f6f4
Create Date: 2024-06-10 11:19:29.662811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '678d5e887ea6'
down_revision = 'a4c08b13f6f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_password_code',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('verification_code', sa.JSON(), nullable=True),
    sa.Column('consumed', sa.Boolean(), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_unique_constraint(None, 'vi_logs', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vi_logs', type_='unique')
    op.drop_table('reset_password_code')
    # ### end Alembic commands ###
