"""Initial Tables

Revision ID: 6a24db7dea49
Revises: 85af962b7d0f
Create Date: 2023-09-22 00:34:12.695963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a24db7dea49'
down_revision = '85af962b7d0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_and_services',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=True),
    sa.Column('MID', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('services', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['MID'], ['users.MID'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_column('eduinstitutes', 'profile_photo')
    op.drop_column('eduinstitutes', 'cover_image')
    op.add_column('ei_admission_details', sa.Column('course_title', sa.String(), nullable=True))
    op.add_column('ei_admission_details', sa.Column('academic_year', sa.String(), nullable=True))
    op.add_column('ei_admission_details', sa.Column('admission_url', sa.String(), nullable=True))
    op.drop_column('organizations', 'profile_photo')
    op.drop_column('organizations', 'cover_image')
    op.create_unique_constraint(None, 'pa_education_info', ['uuid'])
    op.create_unique_constraint(None, 'pa_projects', ['uuid'])
    op.create_unique_constraint(None, 'pa_work_info', ['uuid'])
    op.drop_column('personals', 'profile_photo')
    op.drop_column('personals', 'cover_image')
    op.create_unique_constraint(None, 'social_links', ['uuid'])
    op.add_column('users', sa.Column('profile_photo', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cover_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cover_image')
    op.drop_column('users', 'profile_photo')
    op.drop_constraint(None, 'social_links', type_='unique')
    op.add_column('personals', sa.Column('cover_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('personals', sa.Column('profile_photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pa_work_info', type_='unique')
    op.drop_constraint(None, 'pa_projects', type_='unique')
    op.drop_constraint(None, 'pa_education_info', type_='unique')
    op.add_column('organizations', sa.Column('cover_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('profile_photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ei_admission_details', 'admission_url')
    op.drop_column('ei_admission_details', 'academic_year')
    op.drop_column('ei_admission_details', 'course_title')
    op.add_column('eduinstitutes', sa.Column('cover_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('eduinstitutes', sa.Column('profile_photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('partner_and_services')
    # ### end Alembic commands ###
