"""Report table modified

Revision ID: 6a2db387d1cf
Revises: 63885c482294
Create Date: 2024-01-17 09:54:14.333845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a2db387d1cf'
down_revision = '63885c482294'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports_table', sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('reports_table', sa.Column('reviews_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('reports_table_reporter_uuid_fkey', 'reports_table', type_='foreignkey')
    op.create_foreign_key(None, 'reports_table', 'users', ['user_uuid'], ['uuid'])
    op.create_foreign_key(None, 'reports_table', 'e_battles', ['ebattle_uuid'], ['uuid'])
    op.create_foreign_key(None, 'reports_table', 'users', ['profile_uuid'], ['uuid'])
    op.create_foreign_key(None, 'reports_table', 'reviews', ['reviews_uuid'], ['uuid'])
    op.create_foreign_key(None, 'reports_table', 'posts', ['post_uuid'], ['uuid'])
    op.create_foreign_key(None, 'reports_table', 'certificates', ['certificate_uuid'], ['uuid'])
    op.create_foreign_key(None, 'reports_table', 'comments', ['comment_uuid'], ['uuid'])
    op.drop_column('reports_table', 'report_count')
    op.drop_column('reports_table', 'reporter_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports_table', sa.Column('reporter_uuid', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('reports_table', sa.Column('report_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reports_table', type_='foreignkey')
    op.drop_constraint(None, 'reports_table', type_='foreignkey')
    op.drop_constraint(None, 'reports_table', type_='foreignkey')
    op.drop_constraint(None, 'reports_table', type_='foreignkey')
    op.drop_constraint(None, 'reports_table', type_='foreignkey')
    op.drop_constraint(None, 'reports_table', type_='foreignkey')
    op.drop_constraint(None, 'reports_table', type_='foreignkey')
    op.create_foreign_key('reports_table_reporter_uuid_fkey', 'reports_table', 'users', ['reporter_uuid'], ['uuid'])
    op.drop_column('reports_table', 'reviews_uuid')
    op.drop_column('reports_table', 'user_uuid')
    # ### end Alembic commands ###
