"""About and Tagline completed

Revision ID: 7e97a7453f8d
Revises: 7fdf1c8903aa
Create Date: 2023-10-03 23:05:15.163880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e97a7453f8d'
down_revision = '7fdf1c8903aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eduinstitutes', 'tagline')
    op.drop_column('eduinstitutes', 'about')
    op.drop_column('organizations', 'tagline')
    op.drop_column('organizations', 'about')
    op.drop_column('personals', 'tagline')
    op.drop_column('personals', 'about')
    op.add_column('users', sa.Column('tagline', sa.String(), nullable=True))
    op.add_column('users', sa.Column('about', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about')
    op.drop_column('users', 'tagline')
    op.add_column('personals', sa.Column('about', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('personals', sa.Column('tagline', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('about', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('tagline', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('eduinstitutes', sa.Column('about', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('eduinstitutes', sa.Column('tagline', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
