"""verify table modified

Revision ID: 7ea745b63e9d
Revises: d1ac6f5feaf8
Create Date: 2024-02-16 07:06:22.850809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea745b63e9d'
down_revision = 'd1ac6f5feaf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
