"""Changes in Personal and settings

Revision ID: 7fdf1c8903aa
Revises: 6a24db7dea49
Create Date: 2023-09-29 23:54:25.856780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fdf1c8903aa'
down_revision = '6a24db7dea49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pa_work_info', 'title')
    op.create_unique_constraint(None, 'partner_and_services', ['uuid'])
    op.add_column('personals', sa.Column('title', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('private_setting', sa.String(), nullable=True))
    op.add_column('verifications', sa.Column('document_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifications', 'document_type')
    op.drop_column('settings', 'private_setting')
    op.drop_column('personals', 'title')
    op.drop_constraint(None, 'partner_and_services', type_='unique')
    op.add_column('pa_work_info', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
