"""user management models altered

Revision ID: 8b67a247f057
Revises: cb7505deb50e
Create Date: 2022-12-10 00:00:33.156150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b67a247f057'
down_revision = 'cb7505deb50e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_likes_dislikes',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('post_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('is_liked', sa.Boolean(), nullable=True),
    sa.Column('is_disliked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['post_uuid'], ['posts.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('customs', sa.Column('pronounce', sa.String(), nullable=True))
    op.add_column('customs', sa.Column('DOB', sa.Date(), nullable=True))
    op.add_column('eduinstitutes', sa.Column('administration_management', sa.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True))
    op.add_column('eduinstitutes', sa.Column('faculties', sa.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True))
    op.add_column('eduinstitutes', sa.Column('aluminies', sa.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True))
    op.add_column('eduinstitutes', sa.Column('admission_details', sa.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True))
    op.add_column('eduinstitutes', sa.Column('programs_offer', sa.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True))
    op.add_column('students', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('students', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('students', sa.Column('YOE', sa.Integer(), nullable=True))
    op.drop_column('students', 'mobile_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('mobile_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('students', 'YOE')
    op.drop_column('students', 'company_name')
    op.drop_column('students', 'job_title')
    op.drop_column('eduinstitutes', 'programs_offer')
    op.drop_column('eduinstitutes', 'admission_details')
    op.drop_column('eduinstitutes', 'aluminies')
    op.drop_column('eduinstitutes', 'faculties')
    op.drop_column('eduinstitutes', 'administration_management')
    op.drop_column('customs', 'DOB')
    op.drop_column('customs', 'pronounce')
    op.drop_table('post_likes_dislikes')
    # ### end Alembic commands ###
