"""logs table modified

Revision ID: 8de3ec71275a
Revises: 038a1b14b505
Create Date: 2024-02-26 14:30:13.652767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de3ec71275a'
down_revision = '038a1b14b505'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menem_logs', sa.Column('mobile_app_version', sa.String(), nullable=True))
    op.add_column('menem_logs', sa.Column('is_maintenance', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menem_logs', 'is_maintenance')
    op.drop_column('menem_logs', 'mobile_app_version')
    # ### end Alembic commands ###
