"""Placement Patner and Institute table

Revision ID: 90cb2841722a
Revises: dc2a37d9f8db
Create Date: 2024-01-14 10:36:58.978303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90cb2841722a'
down_revision = 'dc2a37d9f8db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ei_placement_partner', sa.Column('placement_partner_id', sa.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ei_placement_partner', 'placement_partner_id')
    # ### end Alembic commands ###
