"""changes done in reviews table

Revision ID: a0181aa7c042
Revises: e12cb83d898f
Create Date: 2023-01-04 01:28:29.945754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0181aa7c042'
down_revision = 'e12cb83d898f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dont_recommends', sa.Column('ebattle_uuid', sa.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True))
    op.create_unique_constraint(None, 'e_battles', ['uuid'])
    op.create_unique_constraint(None, 'join_e_battles', ['uuid'])
    op.add_column('likes', sa.Column('ebattle_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'likes', ['uuid'])
    op.create_foreign_key(None, 'likes', 'e_battles', ['ebattle_uuid'], ['uuid'])
    op.add_column('reviews', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'reviews', ['uuid'])
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'reviews', type_='unique')
    op.drop_column('reviews', 'is_deleted')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='unique')
    op.drop_column('likes', 'ebattle_uuid')
    op.drop_constraint(None, 'join_e_battles', type_='unique')
    op.drop_constraint(None, 'e_battles', type_='unique')
    op.drop_column('dont_recommends', 'ebattle_uuid')
    # ### end Alembic commands ###
