"""hashtags added

Revision ID: b2cfbca176ea
Revises: e082f7f99ce7
Create Date: 2024-01-25 09:23:23.337084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cfbca176ea'
down_revision = 'e082f7f99ce7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
