"""ebattle and report table changes

Revision ID: b7e60cdbdec6
Revises: ffdb7ee3f674
Create Date: 2023-11-19 22:13:44.143929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e60cdbdec6'
down_revision = 'ffdb7ee3f674'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_battles', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('e_battles', sa.Column('receive_file', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('e_battles', 'receive_file')
    op.drop_column('e_battles', 'timezone')
    # ### end Alembic commands ###
