"""Setting and Report Modified

Revision ID: bfceb29f4932
Revises: 458dfecfec4b
Create Date: 2024-01-19 20:10:44.502847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfceb29f4932'
down_revision = '458dfecfec4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
