"""hashtags table modified

Revision ID: c79007711d82
Revises: bfceb29f4932
Create Date: 2024-01-20 07:34:53.822823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c79007711d82'
down_revision = 'bfceb29f4932'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('hashtags', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('hashtags', sa.String(), nullable=True))
    op.drop_column('hashtags', 'ebattles_count')
    op.drop_column('hashtags', 'posts_count')
    op.drop_column('hashtags', 'certificate_count')
    op.drop_constraint('join_e_battles_post_uuid_fkey', 'join_e_battles', type_='foreignkey')
    op.drop_column('join_e_battles', 'post_uuid')
    op.add_column('posts', sa.Column('hashtags', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('hashtags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'hashtags')
    op.drop_column('posts', 'hashtags')
    op.add_column('join_e_battles', sa.Column('post_uuid', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('join_e_battles_post_uuid_fkey', 'join_e_battles', 'posts', ['post_uuid'], ['uuid'])
    op.add_column('hashtags', sa.Column('certificate_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hashtags', sa.Column('posts_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hashtags', sa.Column('ebattles_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'hashtags')
    op.drop_column('certificates', 'hashtags')
    # ### end Alembic commands ###
