"""setting models altered

Revision ID: cb7505deb50e
Revises: b6f1a442f42c
Create Date: 2022-11-26 03:06:05.961379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7505deb50e'
down_revision = 'b6f1a442f42c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('private_account', sa.Boolean(), nullable=True))
    op.drop_column('settings', 'public_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('public_account', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('settings', 'private_account')
    # ### end Alembic commands ###
