"""Social link table

Revision ID: d1ac6f5feaf8
Revises: df24ea6f0a12
Create Date: 2024-02-03 07:22:53.221945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ac6f5feaf8'
down_revision = 'df24ea6f0a12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_links', sa.Column('threads', sa.String(), nullable=True))
    op.add_column('social_links', sa.Column('discord', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_links', 'discord')
    op.drop_column('social_links', 'threads')
    # ### end Alembic commands ###
