"""boosting and booster name removed

Revision ID: d36f6b506a36
Revises: b7e60cdbdec6
Create Date: 2023-11-22 21:17:01.461998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd36f6b506a36'
down_revision = 'b7e60cdbdec6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boosts', 'boosting_name')
    op.drop_column('boosts', 'booster_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boosts', sa.Column('booster_name', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('boosts', sa.Column('boosting_name', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
