"""Post table altered

Revision ID: e082f7f99ce7
Revises: c79007711d82
Create Date: 2024-01-25 07:05:31.321409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e082f7f99ce7'
down_revision = 'c79007711d82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eduinstitutes', 'institute_name')
    op.drop_column('organizations', 'company_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('eduinstitutes', sa.Column('institute_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
