"""title table modified

Revision ID: f34a3e2056af
Revises: 8de3ec71275a
Create Date: 2024-03-15 16:30:22.883076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f34a3e2056af'
down_revision = '8de3ec71275a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edu_degree',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('edu_specialization',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('explore_category',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('explore_category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('industry',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('job_title',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('App_Data')
    op.drop_column('menem_logs', 'is_maintenance')
    op.drop_column('menem_logs', 'mobile_app_version')
    op.add_column('settings', sa.Column('mobile_app_version', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('is_maintenance', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'is_maintenance')
    op.drop_column('settings', 'mobile_app_version')
    op.add_column('menem_logs', sa.Column('mobile_app_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('menem_logs', sa.Column('is_maintenance', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('App_Data',
    sa.Column('uuid', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('specialization', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('degree', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('explore_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='App_Data_pkey')
    )
    op.drop_table('job_title')
    op.drop_table('industry')
    op.drop_table('explore_category')
    op.drop_table('edu_specialization')
    op.drop_table('edu_degree')
    # ### end Alembic commands ###
