"""certificate modified

Revision ID: f6b408ad69b5
Revises: 09debe05769d
Create Date: 2024-02-18 06:13:50.954971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b408ad69b5'
down_revision = '09debe05769d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
