"""certificate modified

Revision ID: f8128447cc75
Revises: f6b408ad69b5
Create Date: 2024-02-18 06:21:08.020455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8128447cc75'
down_revision = 'f6b408ad69b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
