"""user table added

Revision ID: f9d5e6409497
Revises: b2cfbca176ea
Create Date: 2024-01-30 12:18:22.941553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d5e6409497'
down_revision = 'b2cfbca176ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eduinstitutes', 'location')
    op.drop_column('organizations', 'location')
    op.drop_column('personals', 'location')
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.add_column('personals', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('eduinstitutes', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
