"""Institute and Program Offered Table

Revision ID: fb00e83e308c
Revises: 90cb2841722a
Create Date: 2024-01-14 11:39:31.619445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb00e83e308c'
down_revision = '90cb2841722a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eduinstitutes', 'faculties')
    op.drop_column('eduinstitutes', 'administration_management')
    op.drop_column('eduinstitutes', 'placement_partner')
    op.drop_column('eduinstitutes', 'aluminies')
    op.drop_column('eduinstitutes', 'programs_offer')
    op.drop_column('eduinstitutes', 'admission_details')
    op.add_column('ei_program_offers', sa.Column('document_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ei_program_offers', 'document_link')
    op.add_column('eduinstitutes', sa.Column('admission_details', postgresql.ARRAY(postgresql.UUID()), autoincrement=False, nullable=True))
    op.add_column('eduinstitutes', sa.Column('programs_offer', postgresql.ARRAY(postgresql.UUID()), autoincrement=False, nullable=True))
    op.add_column('eduinstitutes', sa.Column('aluminies', postgresql.ARRAY(postgresql.UUID()), autoincrement=False, nullable=True))
    op.add_column('eduinstitutes', sa.Column('placement_partner', postgresql.ARRAY(postgresql.UUID()), autoincrement=False, nullable=True))
    op.add_column('eduinstitutes', sa.Column('administration_management', postgresql.ARRAY(postgresql.UUID()), autoincrement=False, nullable=True))
    op.add_column('eduinstitutes', sa.Column('faculties', postgresql.ARRAY(postgresql.UUID()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
