"""ebattle table modified

Revision ID: ff8e0151d937
Revises: cb3c46ab909d
Create Date: 2024-04-10 06:49:51.382606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff8e0151d937'
down_revision = 'cb3c46ab909d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('e_battles', sa.Column('start_date', sa.String(), nullable=True))
    op.add_column('e_battles', sa.Column('end_date', sa.String(), nullable=True))
    op.add_column('e_battles', sa.Column('start_time', sa.String(), nullable=True))
    op.add_column('e_battles', sa.Column('end_time', sa.String(), nullable=True))
    op.drop_column('e_battles', 'reward')
    op.drop_column('e_battles', 'from_date')
    op.drop_column('e_battles', 'to_date')
    op.drop_column('e_battles', 'receive_file')
    op.drop_column('join_e_battles', 'image_url')
    op.create_unique_constraint(None, 'location', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='unique')
    op.add_column('join_e_battles', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('e_battles', sa.Column('receive_file', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('e_battles', sa.Column('to_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('e_battles', sa.Column('from_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('e_battles', sa.Column('reward', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('e_battles', 'end_time')
    op.drop_column('e_battles', 'start_time')
    op.drop_column('e_battles', 'end_date')
    op.drop_column('e_battles', 'start_date')
    # ### end Alembic commands ###
