"""user table modified

Revision ID: ffd58e9bbca4
Revises: 0e46c100d49f
Create Date: 2024-06-09 14:41:56.368973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffd58e9bbca4'
down_revision = '0e46c100d49f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_constraint('users_id_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['uuid'])
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_id_key', 'users', ['id'])
    op.drop_column('users', 'uuid')
    # ### end Alembic commands ###
