"""review table updated

Revision ID: ffdb7ee3f674
Revises: 14dcb9330958
Create Date: 2023-11-17 13:37:25.974616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffdb7ee3f674'
down_revision = '14dcb9330958'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reviewer_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('reviews', sa.Column('user_MID', sa.String(), nullable=True))
    op.drop_constraint('reviews_MID_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_MID'], ['MID'])
    op.drop_column('reviews', 'MID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('MID', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_MID_fkey', 'reviews', 'users', ['MID'], ['MID'])
    op.drop_column('reviews', 'user_MID')
    op.drop_column('reviews', 'reviewer_uuid')
    # ### end Alembic commands ###
